### ISSUE TITLE
Batched cache operations

### ISSUE THREAD

**Issue by tshaffe1** [cooperative-computing-lab/hashfs#11]

**Comment by danielgalvaoguerra** [comment]
Implemented batching on the server side and benchmarked batched vs non-batched requests, next step is to add logic in the filesystem to utilize batching

**Comment by tkherman** [comment]
batching from filesystem implemented. cp -r improved by ~22 seconds

**Comment by dthain** [comment]
What was the original performance?
(Also, link the PR here please.)

**Comment by tkherman** [comment]
cp -r on cctools repo
- fuse: 1m40.761s, 1m38.961s, 1m37.555s
- fuse same machine with batching: 1m17.846, 1m16.198s, 1m19s.080s
- fuse different machine with batching: 1m16.036s, 1m14.977s, 1m16.671s
- regular: 0m3.575s, 0m2.869s, 0m3.058s

It was added in commit 924adf79a9d2006a89947013e9572f7aceb97b5f on the master branch

**Comment by dthain** [comment]
Ok, that's a step in the right direction!
