### ISSUE TITLE
Improve Setup Instructions

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/hashfs#4]
Ok, so pretending to be a new user that doesn't know much about hashfs (or python for that matter) I got stuck on the initial setup instructions.  Main thing, try to write them without substitutions, so that a naive user could just copy and paste and succeed.

Trying to follow README.md:

This works so far:
```
curl --location --output virtualenv-16.4.0.tar.gz https://github.com/pypa/virtualenv/tarball/16.4.0
tar xvfz virtualenv-16.4.0.tar.gz
```

This doesn't work b/c I have to figure out YYYYY, but also myVE/bin/activate doesn't exist in the tarball:
```
source pypa-virtualenv-YYYYYY/myVE/bin/activate
```

Didn't know how to fix it, but knowing something about Python, I did this instead:
```
curl https://bootstrap.pypa.io/get-pip.py > get-pip.py
python get-pip.py --user
export PATH=$HOME/.local/bin:$PATH
```

Then these worked:

```
pip install flask
pip install requests
```

Make this a concrete command instead:
```
python CacheServer.py --port 9090 --parent-address 0 --dir /tmp/cache
```

Ok, now I have the cache server running, so I start the shell, but it asks me some questions that the README doesn't explain how to answer:

```
python mkfs_shell.py 
Enter namespace: xxx
Enter root checksum: xxx
```

It would be helpful here to have a separate command `mkfs_init` that sets up a new cache directory with an appropriate empty directory, initial head, and tells you what the root checksum is.  Even better, it could give you the exact command line of `mkfs_shell` to invoke so you know where to start.

**Comment by dthain** [comment]
@tkherman @danielgalvaoguerra

**Comment by danielgalvaoguerra** [comment]
Instructions for installing dependencies and running cache server are now clearer, and will work with simple copy-paste, no need to change any values.

**Comment by tkherman** [comment]
@dthain 
I added a demo.sh that sets up two cache servers and run the mkfs_shell.py
