### ISSUE TITLE
Add command line flags for all options/modes

### ISSUE THREAD

**Issue by tshaffe1** [cooperative-computing-lab/hashfs#9]

**Comment by tkherman** [comment]
Added flags for all options. @trshaffer Please give it a try and let me know if you can get it to work!

**Comment by tshaffe1** [comment]
The options look good, but I'm getting some import issues now. There's no `__init__.py` in `caching`, so imports are failing on Python 2. (Python 3 lets *that* import happen, but runs into trouble with different rules for relative imports later on)
